config/routes.rb
require 'api_constraints'

Shopelia::Application.routes.draw do

  get "/flinkers/:id", to: redirect('/')
  get "/themes/:id", to: redirect('/')
  get "/themes", to: redirect('/')
  get "/hashtags", to: redirect('/')
  get "/hashtags/:id", to: redirect('/')
  
  get "comments/index"

  get "comments/create"

  match "/cgu" => "home#general_terms_of_use"  
  match "/legal" => "home#legal"
  match "/confidentiality" => "home#confidentiality"
  match "/security" => "home#security"
  match "/download" => "home#download"
  match "/connect", to: "home#connect"
  match "/checkout", :controller => "html_app", :action => "index"

  apipie

  devise_for :developers
  devise_for :flinkers
  devise_for :users, controllers: { 
    confirmations: 'devise_override/confirmations',
    passwords: 'devise_override/passwords',
    registrations: 'devise_override/registrations',
    sessions: 'devise_override/sessions', 
  }
  devise_scope :user do
    put "/confirm" => "devise_override/confirmations#confirm"
  end

  resources :home, :only => :index
  resources :send_download_link, :only => :create

  resources :contact, :only => :create
  resources :gateway, :only => :index
  
  resources :addresses
  resources :carts, :only => :show do 
    resources :checkout, :only => :index
  end
  resources :cart_items, :only => [:show, :create] do
    get :unsubscribe, :on => :member
  end
  resources :catalogue, :only => :index
  resources :collections
  resources :collection_items, :only => [:show, :create]
  resources :orders, :only => [:show, :update] do
    get :confirm, :on => :member
    get :cancel, :on => :member
  end
  resources :payment_cards

  namespace :admin do
    match "/", to: "posts#index"
    resources :collections do
      get :up, :on => :member
      get :down, :on => :member
    end
    resources :collection_items
    resources :dashboard, :only => :index
    resources :developers, :only => [:index, :new, :create]
    resources :devices, :only => :show
    resources :events, :only => :index
    resources :incidents, :only => [:index, :update]
    resources :merchants, :only => [:index, :show, :edit, :update]
    resources :orders, :only => [:index, :show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :viking, :only => :index
    resources :blogs
    resources :comments, :only => [:index, :show] do
      post :reply
    end
    resources :posts
    resources :images, :only => [:show, :update]
    resources :flinkers
    resources :statistics, only:[:index]
    resources :csvs, only:[:index, :show]
    resources :themes do
      resources :looks, only:[:index, :create, :destroy], controller:'themes/looks'
      resources :look_images, only:[:index], controller:'themes/look_images'
      resources :flinkers, only:[:index, :create, :destroy], controller:'themes/flinkers'
    end
    resource :themes_preview, only: :show
    resources :looks do
      get :publish, :on => :member
      get :reject, :on => :member
      get :reject_quality, :on => :member
      put :reinitialize_images, :on => :member
      put :highlight_with_tag, :on => :member
      post :add_hashtags_from_staff_hashtags, :on => :member
    end
    namespace :search do
      resources :looks, only:[:index]#, controller:'search/looks'
    end
    resources :look_images
    resources :look_products
    resources :products do
      get :retry, :on => :member
      get :mute, :on => :member
    end
    resources :newsletters do
      get :test
      get :send_to_subscribers
    end
    resources :staff_picks
    resources :flinker_merges, only: [:new, :show, :create]
    resources :pure_shopping_products, only: [:index, :create]
    resources :vendor_products, only: [:index, :destroy]
    resources :apns_notifications, only: [:new, :update] do
      get :test
      get :send_to_flinkers
    end
    resources :staff_hashtags
  end

  constraints DomainConstraints.new('developers') do
    root :to => 'developers/dashboard#index'
  end
  namespace :developers do
    resources :tracking, :only => [:index, :create, :destroy]
    namespace :tracking do
      get :refresh
    end
  end
  
  namespace :zen do
    resources :orders, :only => [:show, :update] do
      get :confirm, :on => :member
      get :cancel, :on => :member
    end
  end

  namespace :api do
    scope :module => :v2, constraints: ApiConstraints.new(version:2)  do
      namespace :users do
        resources :verify, :only => :create
      end
    end
    scope :module => :v1, constraints: ApiConstraints.new(version:1, default:true)  do
      devise_for :users
      resources :addresses, :only => [:index, :create, :show, :update, :destroy]
      resources :cart_items, :only => :create
      resources :collections, :only => [:show, :index]
      resources :devices, :only => :update
      resources :events, :only => [:index, :create]
      resources :payment_cards, :only => [:index, :create, :show, :destroy]
      resources :phone_lookup, :only => :show
      resources :merchants, :only => [:index, :create]
      resources :orders, :only => [:create, :show]
      resources :products, :only => [:index, :create]
      namespace :products do
        resources :requests, :only => :create
      end
      resources :traces, :only => :create
      resources :users, :only => [:show, :update, :destroy]
      namespace :users do
        resources :autocomplete, :only => :create
        resources :exists, :only => :create
        resources :reset, :only => :create
        resources :verify, :only => :create
      end
      get "/georges/status", to: "georges#status"
      namespace :georges do
        resources :messages, :only => [:index, :create, :update] do
          get :read, :on => :member
        end
      end
      namespace :callback do
        resources :orders, :only => :update
      end
      namespace :mango_pay do
        resources :notifications, :only => :index
      end      
      namespace :limonetik do
        resources :orders, :only => :update
      end
      namespace :places do
        resources :autocomplete, :only => :index
        resources :details, :only => :show
      end
    end
    namespace :showcase do
      namespace :products do
        resources :search, :only => :index
      end
    end
    namespace :viking do
      resources :products, :only => [:index, :update]
      namespace :products do
        get :failure
        get :failure_shift
        get :alive
      end
      resources :merchants, :only => [:show, :update, :index]
      resources :mappings, :only => [:index, :update, :show, :create]
    end
    namespace :vulcain do
      resources :merchants, :only => :update
    end
    namespace :customers do
      namespace :merkav do
        resources :merkav_transactions, :as => "transactions", :only => [:index, :create, :show]
        resources :stats, :only => :index
      end
    end
    namespace :flink do
      devise_for :flinkers
      resources :flinkers, :only => :index
      resources :flinkers_search, :only => :index
      resources :publishers, :only => :index
      resources :staff_picks, :only => :index
      resources :activities, :only => :index
      resources :facebook_friends, :only => :index
      resources :instagram_friends, :only => :index
      resources :twitter_friends, :only => :index
      resources :top_flinkers, :only => :index
      resources :avatars, :only => :create
      resources :follows, :only => [:index, :create, :destroy]
      resources :followings, :only => [:index, :create, :destroy]
      resources :followers, :only => :index
      resources :popular_looks, :only => :index
      resources :recent_looks, :only => :index
      resources :best_looks, :only => :index
      resources :trend_setters, :only => :index
      resources :private_messages, :only => :create
      resources :looks, :only => :index do
        resources :comments, :only => [:index, :create], :controller => "looks/comments"
        resources :sharings, :only => :create, :controller => "looks/sharings"
        resources :likes, :only => :create, :controller => "looks/likes"
        resources :products, :only => :index, :controller => "looks/products"
        delete "likes" => "looks/likes#destroy"
      end
      namespace :likes do
        resources :looks, only: :index
      end
      namespace :refresh do
        resources :looks, only: :index
        resources :likes, only: :index
        resources :followings, only: :index
      end
      namespace :connect do
        resources :instagram, only: :create
        resources :twitter, only: :create
      end
      namespace :followings do
        resources :looks, only: :index
        resources :updated_looks, only: :index
      end
      namespace :flinkers do
        resources :looks, only: :index
        resources :passwords, only: :create
      end
      namespace :hashtags do
        resources :looks, only: :index
      end
      namespace :mailjet do
        resources :unsubscribes, only: :create
      end
      
      resources :themes, :only => [:index, :show]
      get 'followers_count' => "followers#count"
      
      scope '/ws' do
        get 'flinkers' => "web_services/flinkers#show"
      end
      namespace :analytics do
        resources :events, only: [:create]
        resources :publishers, only: [:show]
        resources :looks, only: [:show]
      end
    end
  end

  match "about" => "home#about"
  put "api/flink/flinkers/session_touch", to: "api/flink/sessions#update"

  # Flink web site
  root to: 'flink/home#index'
  get "terms", to: "flink/terms#index"
  get "contact", to: "flink/contact#index"
  get "explore", to: "flink/explore#show", as: :flink_explore
  get "explore/:category", to: "flink/explore#show"
  get "looks/:id", to: "flink/looks#show", as: :flink_looks
  
  match '*unmatched_route', :to => 'application#raise_not_found!'
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  before_filter :prepare_filters, :only => :index

  def index
    respond_to do |format|
      format.html
      format.json { render json: OrdersDatatable.new(view_context, @filters) }
    end
  end

  def show
    @order = Order.find_by_uuid!(params[:id])
  end

  def update
    @order = Order.find_by_uuid!(params[:id])
    if params[:state].eql?("cancel")
      @order.cancel
    elsif params[:state].eql?("retry")
      @order.start
    end
    
    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { render json: {} }
    end
  end  

  private

  def prepare_filters
    @date_start = params[:date_start].blank? ? Order.order(:created_at).first.created_at : Date.parse(params[:date_start])
    @date_end = params[:date_end].blank? ? Order.order(:created_at).last.created_at : Date.parse(params[:date_end]) + 1.day
    @filters = {
      :date_start => @date_start,
      :date_end => @date_end,
      :state => params[:state].blank? ? Order::STATES : params[:state]
    }
  end
end

app/controllers/api/v1/callback/orders_controller.rb
class Api::V1::Callback::OrdersController < Api::V1::BaseController
  skip_before_filter :authenticate_user!
  skip_before_filter :authenticate_developer!
  before_filter :retrieve_order
  before_filter :prepare_params

  api :PUT, "/callback/orders/:uuid", "Callback an order"
  param :verb, String, "Action type", :required => true
  param :content, String, "Information about current processing", :required => false
  def update
    @order.callback(@verb, @content)
    head :no_content
  end

  private
  
  def retrieve_order
    @order = Order.where(:uuid => params[:id]).first!
  end
  
  def prepare_params
    @verb = params[:verb]
    @content = params[:content] || {}
  end
  
end

app/controllers/api/v1/limonetik/orders_controller.rb
class Api::V1::Limonetik::OrdersController < Api::V1::BaseController
  skip_before_filter :authenticate_user!
  skip_before_filter :authenticate_developer!
  before_filter :retrieve_order
  before_filter :prepare_params

  api :PUT, "/limonetik/orders/:uuid", "Callback an order from Limonetik back office"
  param :status, String, "Status of the CVD transaction (success, failure, refund)", :required => true
  param :amount, Integer, "Amount in eurocents of the CVD transaction", :required => true
  param :limonetik_order_id, Integer, "Reference to the Limonetik order", :required => true
  def update
    head :no_content
  end

  private
  
  def retrieve_order
    @order = Order.where(:uuid => params[:id]).first!
  end
  
  def prepare_params
    @status = params[:status]
    @amount = params[:amount]
    @l_order_id = [:limonetik_order_id]
    render json:"Invalid parameters", status: :unprocessable_entity and return if @status.blank? || @amount.blank? || @l_order_id.blank?
  end
  
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController
  before_filter :retrieve_order, :only => :show  
  
  def_param_group :order do
    param :order, Hash, :required => true, :action_aware => true do
      param :products, Array, "Array of the products to buy", :required => true
      param :address_id, Integer, "Reference to the delivery address", :required => true
      param :payment_card_id, Integer, "Reference to the payment card to be billed", :required => true
      param :expected_price_total, Float, "Expected total order price. Order will be fullfilled only if checkout price will match", :required => true
    end
  end  
  
  api :POST, "/api/orders", "Create a new order"
  param_group :order
  def create
    # Required for tests
    render :json => {}, status: :created and return if current_user.email.eql?("test@shopelia.fr")
  
    @order = Order.create(params[:order].merge({ user_id: current_user.id, developer_id:@developer.id, tracker:@tracker }))

    if @order.persisted?
      render json: OrderSerializer.new(@order).as_json, status: :created
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  api :GET, "/api/orders/:uuid", "Show an order"
  def show
    render json: OrderSerializer.new(@order).as_json
  end

  private
  
  def retrieve_order
    @order = Order.where(:uuid => params[:id], :user_id => current_user.id).first!
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :retrieve_order

  def update
    if params["order"]["confirmation"].eql?("yes")
      @order.accept
    else
      @order.reject "price_rejected"
    end
    redirect_to @order
  end
  
  def confirm
    @order.accept
    redirect_to @order
  end
  
  def cancel
    @order.reject "price_rejected"
    redirect_to @order
  end

  private
  
  def retrieve_order
    @order = Order.find_by_uuid!(params[:id])
  end  

end

app/controllers/simple/orders_controller.rb
class Simple::OrdersController < ApplicationController
  before_filter :retrieve_order

  def update
    if params["order"]["confirmation"].eql?("yes")
      @order.confirm
    else
      @order.cancel
    end
    redirect_to @order
  end

  private
  
  def retrieve_order
    @order = Order.find_by_uuid!(params[:id])
  end  

end

app/controllers/zen/orders_controller.rb
class Zen::OrdersController < Zen::ZenController
  before_filter :retrieve_order

  def update
    if params["order"]["confirmation"].eql?("yes")
      @order.accept
    else
      @order.reject "price_rejected"
    end
    redirect_to zen_order_url(@order)
  end

  def confirm
    @order.accept
    redirect_to zen_order_url(@order)
  end
  
  def cancel
    @order.reject "price_rejected"
    redirect_to zen_order_url(@order)
  end
  
  private
  
  def retrieve_order
    @order = Order.find_by_uuid!(params[:id])
  end  

end

app/helpers/orders_helper.rb
# -*- encoding : utf-8 -*-
module OrdersHelper
  def state
    case @order.state
      when :initialized
        {state: "initialization",name:"Initialisation"}
      when :preparing
        {state: "processing",name:"Commande en cours"}
      when :pending_agent
        {state:"warning",name:"En attente de traitement"}
      when :querying
        {state:"processing",name:"En attente de votre réponse"}
      when :completed
        {state:"success",name:"Validée"}
      when :failed
        {state:"error",name:failure_reason}
      else
        {state:"error",name:"Annulée"}
    end
  end

  def order_completed?
    @order.state == :completed
  end
  
  def order_querying?
    @order.state == :querying
  end

  def failure_reason
    case @order.error_code
    when "billing"
      "Le paiement de la commande a été refusé par votre banque"
    when "user"
      "Vous avez annulé la commande"
    when "merchant"
      case @order.message
      when "account"
        "Impossible de créer un compte à votre nom chez le marchand"
      when "stock"
        "Le produit demandé n'est plus en stock"
      when "delivery"
        "Le produit demandé ne peut pas être livré par la poste"
      end
    else
      "Le back office Shopelia n'a pas réussi à passer la commande suite à des erreurs techniques de notre part"
    end
  end

end

app/views/admin/orders/index.html.haml
%section.header
  %header
    %h1 Orders
    %h2 Present & past orders

.container-fluid
  .row-fluid
    .span3
      %article.coolbox
        %h3 State filter
        %select.input-medium.filter-option#stateFilter
          %option{value:""} All
          = Order::STATES.each do |s|
            %option{value:s} #{s.camelize}
    .span6
      %article.coolbox
        %h3 Time period
        From
        %input.input-small.filter-option#date-start{type:"text",value:"#{@date_start.strftime("%Y-%m-%d")}"}
        to
        %input.input-small.filter-option#date-end{type:"text",value:"#{@date_end.strftime("%Y-%m-%d")}"}
  .row-fluid
    .span12
      %article.coolbox
        %h3 Orders list
        %table.table.table-striped#orders{data:{source:"#{admin_orders_url(format: 'json')}"}}
          %thead
            %tr
              %th State
              %th Product
              %th Merchant
              %th Price total
              %th User
              %th Date
              %th Message
              %th Error
              %th &nbsp;
          %tbody

.modal.hide.fade#confirmModal{tabindex:"-1",role:"dialog"}
  .modal-header
    %button.close{type:"button",data:{dismiss:"modal"}} &times;
    %h3 Warning !
  .modal-body
    %p
      Do you really want to 
      %strong
        %span#confirmModelState
      the order&nbsp;?
  .modal-footer
    %a.btn{href:"#",data:{dismiss:"modal"}} Close
    %a.btn.btn-danger#confirmModalAction{href:"#"} Confirmation

app/views/admin/orders/show.html.haml
%section.header
  %header
    %h1 Order #{@order.uuid}
    %h2 
      = @order.user.name
    = raw order_state_to_html(@order.state_name)

.container-fluid
  .row-fluid
    .span3
      %article.coolbox
        %h3 Vulcain
        = link_to "Vulcain stats", "https://vulcain.shopelia.fr:444/admin/logs/#{@order.uuid}"

      %article.coolbox
        %h3 Expected
        %strong Price product :
        = number_to_currency @order.expected_price_product
        %br
        %strong Price shipping :
        = number_to_currency @order.expected_price_shipping
        %br
        %strong Price total :
        = number_to_currency @order.expected_price_total
        - if @order.expected_cashfront_value.to_f > 0
          %br
          %strong Cashfront :
          = number_to_currency @order.expected_cashfront_value

      - if @order.state == :completed
        %article.coolbox
          %h3 Billed
          %strong Price product :
          = number_to_currency @order.billed_price_product
          %br
          %strong Price shipping :
          = number_to_currency @order.billed_price_shipping
          %br
          %strong Price total :
          = number_to_currency @order.billed_price_total
          - if @order.expected_cashfront_value.to_f > 0
            %br
            %strong Cashfront :
            = number_to_currency @order.expected_cashfront_value
      - else
        %article.coolbox
          %h3 Prepared
          %strong Price product :
          = number_to_currency @order.prepared_price_product
          %br
          %strong Price shipping :
          = number_to_currency @order.prepared_price_shipping
          %br
          %strong Price total :
          = number_to_currency @order.prepared_price_total
          - if @order.expected_cashfront_value.to_f > 0
            %br
            %strong Cashfront :
            = number_to_currency @order.expected_cashfront_value

      - if @order.state == :completed
        %article.coolbox
          %h3 Shipping info
          = @order.shipping_info

      %article.coolbox
        %h3 Address
        = render @order.meta_order.address
      %article.coolbox
        %h3 Payment card
        = render @order.meta_order.payment_card
      %article.coolbox
        %h3 Merchant account
        = render @order.merchant_account
      %br

    .span9
      %article.coolbox
        %h3 Order items
        %table.table.table-striped
          %thead
            %tr
              %th Product
              %th Quantity
              %th Price
          %tbody
            - @order.order_items.each do |item|
              %tr
                %td
                  = link_to item.product_version.name, item.product_version.product.url
                %td
                  = item.quantity
                %td
                  = number_to_currency(item.price)

      - if @order.meta_order.billing_transactions.any?
        %article.coolbox
          %h3 Card transactions
          %table.table.table-striped
            %thead
              %tr
                %th Processor
                %th Amount
                %th Success
            %tbody
              - @order.meta_order.billing_transactions.each do |transaction|
                %tr
                  %td
                    = transaction.processor
                  %td
                    = number_to_currency(transaction.amount.to_f / 100)
                  %td
                    = transaction.mangopay_contribution_message

      - if @order.payment_transaction.present?
        %article.coolbox
          %h3 Proxy payment
          %table.table.table-striped
            %thead
              %tr
                %th Processor
                %th Amount
                %th Code
            %tbody
              %tr
                %td
                  = @order.payment_transaction.processor
                %td
                  = number_to_currency(@order.payment_transaction.amount.to_f / 100)
                %td
                  = @order.payment_transaction.mangopay_amazon_voucher_code