config/routes.rb
require 'api_constraints'

Shopelia::Application.routes.draw do

  get "/flinkers/:id", to: redirect('/')
  get "/themes/:id", to: redirect('/')
  get "/themes", to: redirect('/')
  get "/hashtags", to: redirect('/')
  get "/hashtags/:id", to: redirect('/')
  
  get "comments/index"

  get "comments/create"

  match "/cgu" => "home#general_terms_of_use"  
  match "/legal" => "home#legal"
  match "/confidentiality" => "home#confidentiality"
  match "/security" => "home#security"
  match "/download" => "home#download"
  match "/connect", to: "home#connect"
  match "/checkout", :controller => "html_app", :action => "index"

  apipie

  devise_for :developers
  devise_for :flinkers
  devise_for :users, controllers: { 
    confirmations: 'devise_override/confirmations',
    passwords: 'devise_override/passwords',
    registrations: 'devise_override/registrations',
    sessions: 'devise_override/sessions', 
  }
  devise_scope :user do
    put "/confirm" => "devise_override/confirmations#confirm"
  end

  resources :home, :only => :index
  resources :send_download_link, :only => :create

  resources :contact, :only => :create
  resources :gateway, :only => :index
  
  resources :addresses
  resources :carts, :only => :show do 
    resources :checkout, :only => :index
  end
  resources :cart_items, :only => [:show, :create] do
    get :unsubscribe, :on => :member
  end
  resources :catalogue, :only => :index
  resources :collections
  resources :collection_items, :only => [:show, :create]
  resources :orders, :only => [:show, :update] do
    get :confirm, :on => :member
    get :cancel, :on => :member
  end
  resources :payment_cards

  namespace :admin do
    match "/", to: "posts#index"
    resources :collections do
      get :up, :on => :member
      get :down, :on => :member
    end
    resources :collection_items
    resources :dashboard, :only => :index
    resources :developers, :only => [:index, :new, :create]
    resources :devices, :only => :show
    resources :events, :only => :index
    resources :incidents, :only => [:index, :update]
    resources :merchants, :only => [:index, :show, :edit, :update]
    resources :orders, :only => [:index, :show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :viking, :only => :index
    resources :blogs
    resources :comments, :only => [:index, :show] do
      post :reply
    end
    resources :posts
    resources :images, :only => [:show, :update]
    resources :flinkers
    resources :statistics, only:[:index]
    resources :csvs, only:[:index, :show]
    resources :themes do
      resources :looks, only:[:index, :create, :destroy], controller:'themes/looks'
      resources :look_images, only:[:index], controller:'themes/look_images'
      resources :flinkers, only:[:index, :create, :destroy], controller:'themes/flinkers'
    end
    resource :themes_preview, only: :show
    resources :looks do
      get :publish, :on => :member
      get :reject, :on => :member
      get :reject_quality, :on => :member
      put :reinitialize_images, :on => :member
      put :highlight_with_tag, :on => :member
      post :add_hashtags_from_staff_hashtags, :on => :member
    end
    namespace :search do
      resources :looks, only:[:index]#, controller:'search/looks'
    end
    resources :look_images
    resources :look_products
    resources :products do
      get :retry, :on => :member
      get :mute, :on => :member
    end
    resources :newsletters do
      get :test
      get :send_to_subscribers
    end
    resources :staff_picks
    resources :flinker_merges, only: [:new, :show, :create]
    resources :pure_shopping_products, only: [:index, :create]
    resources :vendor_products, only: [:index, :destroy]
    resources :apns_notifications, only: [:new, :update] do
      get :test
      get :send_to_flinkers
    end
    resources :staff_hashtags
  end

  constraints DomainConstraints.new('developers') do
    root :to => 'developers/dashboard#index'
  end
  namespace :developers do
    resources :tracking, :only => [:index, :create, :destroy]
    namespace :tracking do
      get :refresh
    end
  end
  
  namespace :zen do
    resources :orders, :only => [:show, :update] do
      get :confirm, :on => :member
      get :cancel, :on => :member
    end
  end

  namespace :api do
    scope :module => :v2, constraints: ApiConstraints.new(version:2)  do
      namespace :users do
        resources :verify, :only => :create
      end
    end
    scope :module => :v1, constraints: ApiConstraints.new(version:1, default:true)  do
      devise_for :users
      resources :addresses, :only => [:index, :create, :show, :update, :destroy]
      resources :cart_items, :only => :create
      resources :collections, :only => [:show, :index]
      resources :devices, :only => :update
      resources :events, :only => [:index, :create]
      resources :payment_cards, :only => [:index, :create, :show, :destroy]
      resources :phone_lookup, :only => :show
      resources :merchants, :only => [:index, :create]
      resources :orders, :only => [:create, :show]
      resources :products, :only => [:index, :create]
      namespace :products do
        resources :requests, :only => :create
      end
      resources :traces, :only => :create
      resources :users, :only => [:show, :update, :destroy]
      namespace :users do
        resources :autocomplete, :only => :create
        resources :exists, :only => :create
        resources :reset, :only => :create
        resources :verify, :only => :create
      end
      get "/georges/status", to: "georges#status"
      namespace :georges do
        resources :messages, :only => [:index, :create, :update] do
          get :read, :on => :member
        end
      end
      namespace :callback do
        resources :orders, :only => :update
      end
      namespace :mango_pay do
        resources :notifications, :only => :index
      end      
      namespace :limonetik do
        resources :orders, :only => :update
      end
      namespace :places do
        resources :autocomplete, :only => :index
        resources :details, :only => :show
      end
    end
    namespace :showcase do
      namespace :products do
        resources :search, :only => :index
      end
    end
    namespace :viking do
      resources :products, :only => [:index, :update]
      namespace :products do
        get :failure
        get :failure_shift
        get :alive
      end
      resources :merchants, :only => [:show, :update, :index]
      resources :mappings, :only => [:index, :update, :show, :create]
    end
    namespace :vulcain do
      resources :merchants, :only => :update
    end
    namespace :customers do
      namespace :merkav do
        resources :merkav_transactions, :as => "transactions", :only => [:index, :create, :show]
        resources :stats, :only => :index
      end
    end
    namespace :flink do
      devise_for :flinkers
      resources :flinkers, :only => :index
      resources :flinkers_search, :only => :index
      resources :publishers, :only => :index
      resources :staff_picks, :only => :index
      resources :activities, :only => :index
      resources :facebook_friends, :only => :index
      resources :instagram_friends, :only => :index
      resources :twitter_friends, :only => :index
      resources :top_flinkers, :only => :index
      resources :avatars, :only => :create
      resources :follows, :only => [:index, :create, :destroy]
      resources :followings, :only => [:index, :create, :destroy]
      resources :followers, :only => :index
      resources :popular_looks, :only => :index
      resources :recent_looks, :only => :index
      resources :best_looks, :only => :index
      resources :trend_setters, :only => :index
      resources :private_messages, :only => :create
      resources :looks, :only => :index do
        resources :comments, :only => [:index, :create], :controller => "looks/comments"
        resources :sharings, :only => :create, :controller => "looks/sharings"
        resources :likes, :only => :create, :controller => "looks/likes"
        resources :products, :only => :index, :controller => "looks/products"
        delete "likes" => "looks/likes#destroy"
      end
      namespace :likes do
        resources :looks, only: :index
      end
      namespace :refresh do
        resources :looks, only: :index
        resources :likes, only: :index
        resources :followings, only: :index
      end
      namespace :connect do
        resources :instagram, only: :create
        resources :twitter, only: :create
      end
      namespace :followings do
        resources :looks, only: :index
        resources :updated_looks, only: :index
      end
      namespace :flinkers do
        resources :looks, only: :index
        resources :passwords, only: :create
      end
      namespace :hashtags do
        resources :looks, only: :index
      end
      namespace :mailjet do
        resources :unsubscribes, only: :create
      end
      
      resources :themes, :only => [:index, :show]
      get 'followers_count' => "followers#count"
      
      scope '/ws' do
        get 'flinkers' => "web_services/flinkers#show"
      end
      namespace :analytics do
        resources :events, only: [:create]
        resources :publishers, only: [:show]
        resources :looks, only: [:show]
      end
    end
  end

  match "about" => "home#about"
  put "api/flink/flinkers/session_touch", to: "api/flink/sessions#update"

  # Flink web site
  root to: 'flink/home#index'
  get "terms", to: "flink/terms#index"
  get "contact", to: "flink/contact#index"
  get "explore", to: "flink/explore#show", as: :flink_explore
  get "explore/:category", to: "flink/explore#show"
  get "looks/:id", to: "flink/looks#show", as: :flink_looks
  
  match '*unmatched_route', :to => 'application#raise_not_found!'
end

app/controllers/flink/home_controller.rb
class Flink::HomeController < ApplicationController
  layout "flink"

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'about', :only => [:about]

  def index
    if params[:from_signin]
      sign_out(current_flinker) if current_flinker
      render 'after_signin', layout:'flink'
    else
      logger.error request.original_url
      redirect_to :root
    end
  end

  def download
    user_agent = request.env['HTTP_USER_AGENT'].downcase
    if user_agent.match(/android/)
      redirect_to "market://details?id=com.shopelia.android.application"
    elsif user_agent.match(/iphone/) || user_agent.match(/ipod/) || user_agent.match(/ipad/)
      redirect_to "https://itunes.apple.com/fr/app/shopelia-lachat-facile-!/id731471392?mt=8"
    else
      redirect_to "/"
    end
  end

  def connect
    redirect_to session[:return_to] || home_index_path if current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_private.html.haml
= render "cart_items/form"
.spacer25
#cart
  = render @current_cart

app/views/home/_public.en.html.haml
#video-iframe
  <iframe src="//player.vimeo.com/video/76611634" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

app/views/home/_public.fr.html.haml
%article#homeArticle
  .topHome
    .spacer-header
    .container
      .row
        .col-md-6.center
          .promise
            = t 'app.public.promise'
            %h3= t 'app.public.tagline'
              
          .spacer40
          .btn.btn-default.btn-lg.btn-download#get-link{rel:"tooltip", data:{animation:'true', placement:'right', trigger:'click', html:'true'}}
            = t 'app.public.download_app'
          .row
            .col-md-4.col-md-offset-2
              .spacer40
              = link_to image_tag("appstore-icon.png"), "https://itunes.apple.com/fr/app/shopelia-lachat-facile-!/id731471392?mt=8"
            .col-md-4
              .spacer40
              = link_to image_tag("googleplay-icon.png"), "https://play.google.com/store/apps/details?id=com.shopelia.android.application"
            .spacer40
        .col-md-6
          .iphone-screen
            = image_tag("ios-screen.png", :class => "demo-screen")

  .spacer100
  %section
    .container
      .row
        .col-md-3.center= image_tag("simple-icon.png", width:"200px")
        .col-md-8.col-md-offset-1
          %h1.red= t 'app.public.simple.title'
          %p= t 'app.public.simple.text'
            
  .spacer50
  %section
    .container
      .row
        .col-md-3.center.col-md-push-8.col-md-offset-1= image_tag("convenient-icon.png", width:"200px")
        .col-md-8.col-md-pull-3
          %h1.green= t 'app.public.practical.title'
          %p= t 'app.public.practical.text'

  .spacer50
  %section
    .container
      .row
        .col-md-3.center= image_tag("security-icon.png", width:"200px")
        .col-md-8.col-md-offset-1
          %h1.blue= t 'app.public.secure.title'
          %p
            = t 'app.public.secure.text'
            = link_to("En savoir plus","/security")

  .spacer100

  %section#download
    .spacer40
    .container
      .row
        .col-md-6.col-md-offset-3
          .well#well_download
            .btn.btn-primary.btn-lg.btn-block.btn-download{rel:"tooltip"}
              = t 'app.public.download_app'

    .spacer50

#sendAppInvalidEntryModal.modal.fade{role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        %h4= t 'app.public.send_app.invalid_entry'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}= t 'app.close'

#sendAppErrorModal.modal.fade{role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        %h4= t 'app.public.send_app.error'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}= t 'app.close'

#sendAppSuccessModal.modal.fade{role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        %h4= t 'app.public.send_app.success'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"}= t 'app.close'

#downloadTooltip.hidden
  =raw(t 'app.public.download.tooltip')
  .spacer10
  = render "send_download_link/form"

app/views/home/after_signin.html.haml
.password-reset-section
  .fluid
    .row
      .col-md-6
        =image_tag(image_path('flink-logo-full.png'))
        %p.password-changed= t('app.password.success_changed')
        

app/views/home/confidentiality.fr.html.haml
.container
  .row.cgu
    .col-md-6.col-md-offset-3
      .spacer40
      %h3
        Charte de Confidentialité
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b 1. Objet
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 Cette rubrique illustre l'engagement de la société PRIXING eu égard au respect de votre vie privée et à la protection des données personnelles vous concernant (les "Données"), recueillies et traitées à l'occasion de votre utilisation du site Shopelia (le "Site") dans les conditions visées au sein de nos 
        = link_to "Conditions Générales d'Utilisation", cgu_path
      %p.p3
        %span.s1 La présente Charte a ainsi été élaborée afin que vous puissiez naviguer sur le site Shopelia et utiliser les services du Site en toute confiance. Sa finalité est donc de vous renseigner sur les informations susceptibles d’être collectées et sur l’usage pouvant en être fait. Elle vous informe aussi de vos droits sur les Données vous concernant qui ont été recueillies.
      %p.p3
        %span.s1 la société PRIXING est le responsable de traitement des données collectées dans le cadre du service Shopelia, il respecte à ce titre les dispositions légales et réglementaires en matière de vie privée et de protection des données à caractère personnel prévues notamment par la loi du 6 janvier 1978. Elle dispose d'un Correspondant Informatique et Libertés (CIL) en la personne du cabinet d'avocats LEXENSIS Avocats Conseils (4 place du 18 juin 1940 - 75006 PARIS).
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b 2. Données Collectées
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 Les Données recueillies et ultérieurement traitées par notre Site sont celles que vous nous transmettez volontairement lors de l’ouverture de votre compte Utilisateur (le "Compte"), via le Formulaire d'inscription, et concernent au minimum : vos nom et prénom(s), votre adresse de messagerie électronique valide, cette dernière constituant votre identifiant (nom d’Utilisateur) pour accéder à votre Compte et à nos services, un mot de passe choisi par vos soins.
      %p.p3
        %span.s1 Certaines des Données demandées sont obligatoires pour la gestion et l'utilisation de notre service, elles font alors l'objet d'un marquage spécifique qui se matérialise par la présence d'une astérisque à côté de leur intitulé. Les informations ne présentant pas cette astérisque sont facultatives.
      %p.p3
        %span.s1 Les Données recueillies automatiquement par le Site sont votre adresse IP (adresse de votre ordinateur) à laquelle sont associées la version de votre navigateur, l’adresse de la page affichée et la date de la requête.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b 3. Finalités des Traitements
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 Les Données identifiées comme étant obligatoires dans le Formulaire d'inscription sont nécessaires aux fins de bénéficier des fonctionnalités du Site. Nous utiliserons ces informations pour gérer et maintenir notre Site, afin de vous permettre de bénéficier de fonctionnalités personnalisées, ainsi que pour traiter tout signalement ou correspondance de votre part. Les Données recueillies automatiquement par le Site nous permettent d'effectuer des statistiques de consultation de ses pages web.
      %p.p3
        %span.s1 Les informations dont nous disposons à votre sujet pourront être utilisées pour garantir la pertinence des informations et/ou offres commerciales qui pourraient vous être proposées par rapport à vos centres d'intérêt. Nous sommes persuadés que ces informations et/ou offres commerciales personnalisées contribueront à l'amélioration de votre expérience sur notre site. Toutes les informations utilisées sont traitées conformément à notre Charte de confidentialité.
      %p.p3
        %span.s1 Nous pourrons être amenés à collaborer avec d'autres entreprises, par exemple des opérateurs de sites Web, pour vous proposer ces informations et/ou offres commerciales.
      %p.p3
        %span.s1  Nous n'utilisons pas votre adresse électronique ni toute autre information susceptible de vous identifier personnellement sans votre accord, que ce soit pour envoyer des messages publicitaires ou marketing, sauf dans le cadre d'un programme ou d'une fonction spécifique que vous pouvez préalablement activer ou bloquer.
      %p.p3
        %span.s1 Cependant, nous pouvons utiliser votre adresse électronique sans votre accord exprès dans les cas suivants :
      %p.p3
        %span.s1 - Inscription en qualité de membre du Site : Le nouveau membre Utilisateur reçoit un courrier électronique de bienvenue contenant un lien d'activation de son Compte et un rappel des identifiants y permettant l’accès, à savoir son nom d’Utilisateur (constitué par son adresse électronique) ainsi que son mot de passe.
      %p.p3
        %span.s1 - Fermeture du Compte : En cas de demande formulée à la société PRIXING, par l’Utilisateur, en vue de la fermeture définitive ou de la désactivation temporaire de son Compte, un courrier électronique de notification lui est envoyé par le Site afin de l’informer de la réalisation de l’opération demandée. De même, au delà d'un an d'inactivité du Compte, un courrier électronique de notification est envoyé à l’Utilisateur selon les conditions posées à l’article 8 de la présente Charte.
      %p.p3
        %span.s1 - Evénements, Jeux et Concours Shopelia: : Envoi à l’Utilisateur des courriers électroniques afin de l'informer de l’existence de jeux et concours ou événements spéciaux organisés par le Site.
      %p.p3
        %span.s1 - Informations sur le Site et les services proposés : Shopelia peut envoyer à l’Utilisateur des courriers électroniques afin de l'informer des évolutions du Site, lui transmettre les lettres d’information et les notifications des services auxquels il est inscrit. Il vous est toujours possible de faire cesser les envois en vous désinscrivant de la lettre d’information en cliquant sur le lien de désinscription contenu dans le message électronique que nous vous avons adressé.
      %p.p3
        %span.s1  - Demande d’assistance ou soumission de questions / suggestions : Shopelia répond par courrier électronique à l’Utilisateur qui sollicite une assistance pour se connecter sur le Site, modifier ou accéder à son Compte.
      %p.p3
        %span.s1 - Informations relatives à des services analogues à Shopelia proposés par des sous-traitants et/ou des partenaires commerciaux. Vous conservez la faculté de refuser une telle communication, soit en ne donnant pas votre consentement lors de l'inscription et/ou validation de votre commande, soit en manifestant a posteriori votre refus par courrier postal ou courrier électronique à la société PRIXING.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  4. Destinataires des Données
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 La société PRIXING s’engage à protéger votre vie privée et la confidentialité de vos Données.
      %p.p3
        %span.s1 En conséquence, nous nous engageons à ne jamais partager ou divulguer vos Données à des tiers, excepté dans les situations suivantes limitativement énumérées : Lorsque nous y sommes contraints par une autorité judiciaire, des autorités de police et de manière générale par toute autorité administrative habilitée par la loi, Lorsque vous nous avez donné votre accord préalable pour le partage de ces informations, Lorsque vous contrevenez à nos Conditions Générales d'Utilisation (nous sommes ainsi en mesure de transmettre votre adresse IP aux fournisseurs d'accès à des fins d'identification - et obtenir ainsi votre radiation éventuelle - voire, si nous l'estimons nécessaire compte tenu de la nature de vos abus, transmettre votre adresse IP directement auprès des autorités compétentes).
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b 5. Sécurité et conservation des Données
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 Soucieux de la confiance dont fait preuve l’Utilisateur lorsqu’il se connecte sur notre Site, nous attachons une grande importance à la sécurité et la protection de ses Données et mettons en œuvre toutes mesures nécessaires aux fins de restreindre les risques de perte, détérioration ou mauvaise utilisation de celles-ci.
      %p.p3
        %span.s1 Ainsi, afin de garantir une sécurité optimale, la société PRIXING utilise la technologie standard SSL (Secure Socket Layer) en 256 bits. L'utilisation du protocole SSL, l'une des méthodes de cryptage les plus efficaces et les plus utilisées actuellement, permet de garantir une protection maximale de vos Données.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  6. Sites partenaires
      %p.p2
        %span.s1 
        %br/
      %p.p3
        %span.s1 Vous pouvez accéder, par les liens hypertexte présents sur le Site, aux sites de Partenaires qui ne sont pas régis par les présentes dispositions de protection des Données. Vous êtes, en conséquence, invité à examiner les règles applicables à l’utilisation et à la divulgation des informations que vous aurez communiquées sur ces sites.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  7. Droits d’accès, de modification et de suppression de vos données.
      %p.p2
        %span.s1 
        %br/
      %p.p3
        %span.s1 La société PRIXING se conforme aux recommandations de loi du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés. Ainsi, vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données à caractère personnel vous concernant. La mise en œuvre de ces droits ainsi que la consultation du registre des traitements des données à caractère personnel sont possibles en adressant un courrier à notre CIL par voie électronique à l’adresse cil(at)lexensis(point)com, et/ou par voie postale en écrivant à l’attention de LEXENSIS Avocats Conseils (4 place du 18 juin 1940 — 75006 Paris). Nous vous rappelons qu'il est important que vous indiquiez vos nom, prénom, adresse et, le cas échéant, votre numéro d'Utilisateur afin de faciliter votre identification par le CIL.
      %p.p3
        %span.s1 A tout moment, vous pouvez mettre à jour ou corriger votre profil et votre adresse électronique dans la page de profil de votre Compte.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  8. Durée de conservation des données et inactivité du compte
      %p.p2
        %span.s1 
        %br/
      %p.p3
        %span.s1 Nous conservons vos données personnelles pendant toute la durée de nos relations contractuelles et elles seront supprimées dans les 12 mois suivant la fin de nos relations contractuelles ou de la date de votre dernière connexion à nos services. Celles-ci ne feront en aucun cas l'objet d'une cession ou divulgation à des tiers, si ce n'est sous forme de statistiques agrégées et non personnelles.
      %p.p3
        %span.s1 Au delà d'un an d'inactivité de votre Compte, celui-ci peut être supprimé à tout moment. Néanmoins, cette suppression ne pourra intervenir qu’après l’envoi par la société PRIXING d’un courrier électronique vous informant de cette inactivité et du risque de suppression de votre Compte. A défaut de réactivation de votre Compte dans un délai de 8 jours à compter de la réception de ce courrier électronique, la société PRIXING pourra alors le supprimer à tout moment, sans nouvelle information préalable.
      %p.p3
        %span.s1 Une fois votre Compte supprimé, vous ne pourrez plus accéder aux services du Site nécessitant la possession d'un Compte, ni aux différents contenus que vous auriez pu stocker ou publier sur ces services.
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  9. Mises à jour de la Charte de Confidentialité
      %p.p2
        %span.s1 
        %br/
      %p.p3
        %span.s1 La société PRIXING est susceptible de modifier la présente Charte de Confidentialité à tout moment.
      %p.p3
        %span.s1 Toutes les modifications de la Charte seront affichées sur cette page. Si les changements sont importants, la société PRIXING s’engage à vous fournir un avis plus conséquent (notification par courrier électronique, par exemple).
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1
          %b  10. Questions, réclamations ou suggestions
      %p.p2
        %span.s1 
        %br/
      %p.p3
        %span.s1 Nous tenons à la plus grande clarté au sujet de la confidentialité de vos Données. Aussi, pour toutes questions, suggestions ou autres préoccupations relatives au traitement des Données ou à la façon dont la société PRIXING procède à la collecte et à l'utilisation des Données vous concernant, n’hésitez pas à contacter notre CIL par courrier électronique à l'adresse suivante : cil(at)lexensis(point)com
      .spacer40

app/views/home/connect.html.haml
.fluid
  .row
    .col-md-6
      .spacer50
      %h2 #{t('app.signin.title')}
      .spacer25
      =render "devise/sessions/form"
    .col-md-6
      .spacer50
      %h2 #{t('app.signup.title')}
      .spacer25
      =render "devise/registrations/form"

app/views/home/index.html.haml
- if current_user
  = render "private"
- else
  = render "public"

app/views/home/legal.fr.html.haml
.container
  .row.cgu
    .col-md-6.col-md-offset-3
      .spacer40
      %h3
        Mentions légales 
      %p.p2
        %span.s1
        %br/
      %p.p3
        %span.s1 Le présent site est édité par la société PRIXING, Société par Actions Simplifiée au capital de 291.676,00 Euros, dont le siège social est situé 21, rue d’Aboukir - 75002 PARIS. Elle peut être contactée par téléphone au numéro suivant 01.82.09.15.44 et/ou à son adresse électronique : contact@shopelia.fr
      %p.p3
        %span.s1 La société PRIXING est immatriculée au Registre du Commerce et des Sociétés de Paris sous le numéro B 529 991 119. Le directeur de la publication est Monsieur Eric LARCHEVÊQUE en sa qualité de Président de la société PRIXING.
      %p.p3
        %span.s1 Le site est hébergé auprès d'OVH, dont le siège social est situé au 140 Quai du Sartel – 59100 Roubaix – France, immatriculée au RCS de Roubaix – Tourcoing sous le numéro SIRET 424 761 419 00011.
      .spacer40