config/routes.rb
require 'api_constraints'

Shopelia::Application.routes.draw do

  get "/flinkers/:id", to: redirect('/')
  get "/themes/:id", to: redirect('/')
  get "/themes", to: redirect('/')
  get "/hashtags", to: redirect('/')
  get "/hashtags/:id", to: redirect('/')
  
  get "comments/index"

  get "comments/create"

  match "/cgu" => "home#general_terms_of_use"  
  match "/legal" => "home#legal"
  match "/confidentiality" => "home#confidentiality"
  match "/security" => "home#security"
  match "/download" => "home#download"
  match "/connect", to: "home#connect"
  match "/checkout", :controller => "html_app", :action => "index"

  apipie

  devise_for :developers
  devise_for :flinkers
  devise_for :users, controllers: { 
    confirmations: 'devise_override/confirmations',
    passwords: 'devise_override/passwords',
    registrations: 'devise_override/registrations',
    sessions: 'devise_override/sessions', 
  }
  devise_scope :user do
    put "/confirm" => "devise_override/confirmations#confirm"
  end

  resources :home, :only => :index
  resources :send_download_link, :only => :create

  resources :contact, :only => :create
  resources :gateway, :only => :index
  
  resources :addresses
  resources :carts, :only => :show do 
    resources :checkout, :only => :index
  end
  resources :cart_items, :only => [:show, :create] do
    get :unsubscribe, :on => :member
  end
  resources :catalogue, :only => :index
  resources :collections
  resources :collection_items, :only => [:show, :create]
  resources :orders, :only => [:show, :update] do
    get :confirm, :on => :member
    get :cancel, :on => :member
  end
  resources :payment_cards

  namespace :admin do
    match "/", to: "posts#index"
    resources :collections do
      get :up, :on => :member
      get :down, :on => :member
    end
    resources :collection_items
    resources :dashboard, :only => :index
    resources :developers, :only => [:index, :new, :create]
    resources :devices, :only => :show
    resources :events, :only => :index
    resources :incidents, :only => [:index, :update]
    resources :merchants, :only => [:index, :show, :edit, :update]
    resources :orders, :only => [:index, :show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :viking, :only => :index
    resources :blogs
    resources :comments, :only => [:index, :show] do
      post :reply
    end
    resources :posts
    resources :images, :only => [:show, :update]
    resources :flinkers
    resources :statistics, only:[:index]
    resources :csvs, only:[:index, :show]
    resources :themes do
      resources :looks, only:[:index, :create, :destroy], controller:'themes/looks'
      resources :look_images, only:[:index], controller:'themes/look_images'
      resources :flinkers, only:[:index, :create, :destroy], controller:'themes/flinkers'
    end
    resource :themes_preview, only: :show
    resources :looks do
      get :publish, :on => :member
      get :reject, :on => :member
      get :reject_quality, :on => :member
      put :reinitialize_images, :on => :member
      put :highlight_with_tag, :on => :member
      post :add_hashtags_from_staff_hashtags, :on => :member
    end
    namespace :search do
      resources :looks, only:[:index]#, controller:'search/looks'
    end
    resources :look_images
    resources :look_products
    resources :products do
      get :retry, :on => :member
      get :mute, :on => :member
    end
    resources :newsletters do
      get :test
      get :send_to_subscribers
    end
    resources :staff_picks
    resources :flinker_merges, only: [:new, :show, :create]
    resources :pure_shopping_products, only: [:index, :create]
    resources :vendor_products, only: [:index, :destroy]
    resources :apns_notifications, only: [:new, :update] do
      get :test
      get :send_to_flinkers
    end
    resources :staff_hashtags
  end

  constraints DomainConstraints.new('developers') do
    root :to => 'developers/dashboard#index'
  end
  namespace :developers do
    resources :tracking, :only => [:index, :create, :destroy]
    namespace :tracking do
      get :refresh
    end
  end
  
  namespace :zen do
    resources :orders, :only => [:show, :update] do
      get :confirm, :on => :member
      get :cancel, :on => :member
    end
  end

  namespace :api do
    scope :module => :v2, constraints: ApiConstraints.new(version:2)  do
      namespace :users do
        resources :verify, :only => :create
      end
    end
    scope :module => :v1, constraints: ApiConstraints.new(version:1, default:true)  do
      devise_for :users
      resources :addresses, :only => [:index, :create, :show, :update, :destroy]
      resources :cart_items, :only => :create
      resources :collections, :only => [:show, :index]
      resources :devices, :only => :update
      resources :events, :only => [:index, :create]
      resources :payment_cards, :only => [:index, :create, :show, :destroy]
      resources :phone_lookup, :only => :show
      resources :merchants, :only => [:index, :create]
      resources :orders, :only => [:create, :show]
      resources :products, :only => [:index, :create]
      namespace :products do
        resources :requests, :only => :create
      end
      resources :traces, :only => :create
      resources :users, :only => [:show, :update, :destroy]
      namespace :users do
        resources :autocomplete, :only => :create
        resources :exists, :only => :create
        resources :reset, :only => :create
        resources :verify, :only => :create
      end
      get "/georges/status", to: "georges#status"
      namespace :georges do
        resources :messages, :only => [:index, :create, :update] do
          get :read, :on => :member
        end
      end
      namespace :callback do
        resources :orders, :only => :update
      end
      namespace :mango_pay do
        resources :notifications, :only => :index
      end      
      namespace :limonetik do
        resources :orders, :only => :update
      end
      namespace :places do
        resources :autocomplete, :only => :index
        resources :details, :only => :show
      end
    end
    namespace :showcase do
      namespace :products do
        resources :search, :only => :index
      end
    end
    namespace :viking do
      resources :products, :only => [:index, :update]
      namespace :products do
        get :failure
        get :failure_shift
        get :alive
      end
      resources :merchants, :only => [:show, :update, :index]
      resources :mappings, :only => [:index, :update, :show, :create]
    end
    namespace :vulcain do
      resources :merchants, :only => :update
    end
    namespace :customers do
      namespace :merkav do
        resources :merkav_transactions, :as => "transactions", :only => [:index, :create, :show]
        resources :stats, :only => :index
      end
    end
    namespace :flink do
      devise_for :flinkers
      resources :flinkers, :only => :index
      resources :flinkers_search, :only => :index
      resources :publishers, :only => :index
      resources :staff_picks, :only => :index
      resources :activities, :only => :index
      resources :facebook_friends, :only => :index
      resources :instagram_friends, :only => :index
      resources :twitter_friends, :only => :index
      resources :top_flinkers, :only => :index
      resources :avatars, :only => :create
      resources :follows, :only => [:index, :create, :destroy]
      resources :followings, :only => [:index, :create, :destroy]
      resources :followers, :only => :index
      resources :popular_looks, :only => :index
      resources :recent_looks, :only => :index
      resources :best_looks, :only => :index
      resources :trend_setters, :only => :index
      resources :private_messages, :only => :create
      resources :looks, :only => :index do
        resources :comments, :only => [:index, :create], :controller => "looks/comments"
        resources :sharings, :only => :create, :controller => "looks/sharings"
        resources :likes, :only => :create, :controller => "looks/likes"
        resources :products, :only => :index, :controller => "looks/products"
        delete "likes" => "looks/likes#destroy"
      end
      namespace :likes do
        resources :looks, only: :index
      end
      namespace :refresh do
        resources :looks, only: :index
        resources :likes, only: :index
        resources :followings, only: :index
      end
      namespace :connect do
        resources :instagram, only: :create
        resources :twitter, only: :create
      end
      namespace :followings do
        resources :looks, only: :index
        resources :updated_looks, only: :index
      end
      namespace :flinkers do
        resources :looks, only: :index
        resources :passwords, only: :create
      end
      namespace :hashtags do
        resources :looks, only: :index
      end
      namespace :mailjet do
        resources :unsubscribes, only: :create
      end
      
      resources :themes, :only => [:index, :show]
      get 'followers_count' => "followers#count"
      
      scope '/ws' do
        get 'flinkers' => "web_services/flinkers#show"
      end
      namespace :analytics do
        resources :events, only: [:create]
        resources :publishers, only: [:show]
        resources :looks, only: [:show]
      end
    end
  end

  match "about" => "home#about"
  put "api/flink/flinkers/session_touch", to: "api/flink/sessions#update"

  # Flink web site
  root to: 'flink/home#index'
  get "terms", to: "flink/terms#index"
  get "contact", to: "flink/contact#index"
  get "explore", to: "flink/explore#show", as: :flink_explore
  get "explore/:category", to: "flink/explore#show"
  get "looks/:id", to: "flink/looks#show", as: :flink_looks
  
  match '*unmatched_route', :to => 'application#raise_not_found!'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :collection_items, :dependent => :destroy
  has_many :collection_tags, :dependent => :destroy
  has_many :products, :through => :collection_items
  has_many :tags, :through => :collection_tags

  validates :uuid, :presence => true, :uniqueness => true

  before_validation :generate_uuid
  before_validation :generate_rank
  after_save :set_home_tag

  has_attached_file :image, :url => "/images/collections/:id/img.jpg", :path => "#{Rails.public_path}/images/collections/:id/img.jpg"
  after_post_process :save_image_dimensions

  attr_accessible :description, :name, :user_id, :public, :image, :rank

  scope :public, where(public:true)

  def to_param
    param = self.uuid + (self.name.present? ? "-#{self.name}" : "")
    param.unaccent.parameterize
  end

  def belongs_to? user
    user && self.user_id == user.id
  end

  def items
    self.products.available
  end

  private

  def generate_uuid
    self.uuid = SecureRandom.hex(4) if self.uuid.nil?
  end

  def generate_rank
    self.rank = 1 if self.public? && self.rank.nil?
  end

  def save_image_dimensions
    geo = Paperclip::Geometry.from_file(image.queued_for_write[:original])
    self.image_size = "#{geo.width.to_i}x#{geo.height.to_i}"
  end

  def set_home_tag
    if self.public_changed?
      tag = Tag.find_by_name("__Home")
      if self.public?
        self.tags << tag
      else
        self.collection_tags.where(tag_id:tag.id).destroy_all
      end
    end
  end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::AdminController
  before_filter :retrieve_collection, :only => [:show, :edit, :update, :up, :down]

  def index
    @collections = Collection.where("length(collections.name) > 0").order("rank asc, created_at")
    @tags = @collections.joins(:tags).map(&:tags).map{|t| t.first.name}.uniq
  end

  def show
  end

  def new
    @collection = Collection.create
  end

  def update
    @collection.update_attributes params[:collection]
      respond_to do |format|
        format.html {redirect_to edit_admin_collection_url(@collection)}
        format.js
      end
  end

  def up
    @collection.update_attributes(rank:(@collection.rank - 1))
    redirect_to admin_collections_path
  end

  def down
    @collection.update_attributes(rank:(@collection.rank + 1))
    redirect_to admin_collections_path
  end

  private

  def retrieve_collection
    @collection = Collection.find_by_uuid!(params[:id].scan(/^[^\-]+/))
  end
end

app/controllers/api/v1/collections_controller.rb
class Api::V1::CollectionsController < Api::V1::BaseController
  skip_before_filter :authenticate_user!
  before_filter :prepare_scope
  before_filter :retrieve_tags, :only => :index
  before_filter :retrieve_collections, :only => :index
  before_filter :retrieve_collection, :only => :show

  api :GET, "/collections", "Get all collections by tags"
  def index
    render json: @collections.sort_by{|h| [h.rank,h.created_at]}.map{ |c| CollectionSerializer.new(c, scope:@scope).as_json[:collection] }
  end

  api :GET, "/collections/:uuid", "Get collection's product"
  def show
    render json: @collection.items.map{ |p| ProductSerializer.new(p, scope:@scope).as_json[:product] }
  end

  private

  def retrieve_tags
    @tags = (params[:tags] || []).map{|n| Tag.find_or_create_by_name(n)}
  end

  def retrieve_collections
    @collections = @tags.map{|tag| tag.collections.public}.inject(:&) || []
  end

  def retrieve_collection
    @collection = Collection.find_by_uuid(params[:id])
  end

  def prepare_scope
    @scope = { developer:@developer, device:@device, short:true }
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create]
  before_filter :find_collection, :only => [:show, :edit, :update]
  before_filter :ensure_collection_edit_rights!, :only => [:update]

  def index
    @collections = Collection.order("created_at DESC")
  end

  def create
    @collection = @current_user.collections.build(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_path(@collection) }
        format.js
      else
        format.html { render partial:"new_collection" }
        format.js
      end
    end
  end

  def update
    if @collection.update_attributes params[:collection]
      redirect_to collection_path(@collection)
    else
      render "edit"
    end
  end

  private

  def find_collection
    @collection = Collection.find_by_uuid!(params[:id].scan(/^[^\-]+/))
  end

  def ensure_collection_edit_rights!
    render status: :unauthorized and return if @current_user.id != @collection.user_id
  end
end

app/helpers/collection_helper.rb
module CollectionHelper

  def generate_requests_for_current_collection
    Product.where(id:@collection.reload.collection_items.map(&:product_id)).expired.map(&:id).each do |id|
      EventsWorker.perform_async({
        :product_id => id,
        :developer_id => @developer.id,
        :action => Event::REQUEST,
        :tracker => "display-collection",
        :device_id => @device.id,
        :ip_address => @remote_ip
      })
    end
    @collection.products.each do |product|
      product.authorize_push_channel
    end
  end
end

app/views/admin/collections/_builder.html.haml
.container-fluid
  .row-fluid
    .span2
      .spacer15
      .row
        .span12
          =render("admin/collections/form" , georges: georges)
          %input#catalogue-search.catalogue-refresh.form-control{placeholder: "Search catalogue by keywords", spellcheck: "false", type: "text", style:"width: #{georges ? '80' : '100'}%"}
          %table
            %tr
              %td
                min
              %td 
                %input#catalogue-price-min.catalogue-refresh.form-control{style:"width:50px;"}
              %td
                max
              %td
                %input#catalogue-price-max.catalogue-refresh.form-control{style:"width:50px;"}
          %p#search-info
          %p#filter-tags
          .spacer10
      .row
        .span6
          %button.btn.btn-info.display-none#catalogue-previous-page
            %i.icon-chevron-left.icon-white
        .span6
          %button.btn.btn-info.display-none#catalogue-next-page
            %i.icon-chevron-right.icon-white
      .spacer5
      .row
        .span6
          %button.btn.btn-success#catalogue-add-shuffle{"data-loading-text" => "..."}
            %i.icon-plus.icon-white
            rnd
        .span6
          %button.btn.btn-success#catalogue-add-top{"data-loading-text" => "..."}
            %i.icon-plus.icon-white
            top
      .spacer5
      .row
        .span6
          %button.btn.btn-success#catalogue-add-urls
            %i.icon-plus.icon-white
            url
        .span6
          %button.btn.btn-success#catalogue-add-custom
            %i.icon-plus.icon-white
            cst
      .spacer10
      .row
        .span12
        %p#tags-merchant
        %p#tags-category
    .span8
      .row
        #catalogue
          - 16.times do |i|
            .span3{style:"margin-left:10px;"}
              .catalogue-box.display-none{id: "catalogue-box-#{i}"}
                .catalogue-product
                  %img.catalogue-img{id: "catalogue-box-img-#{i}"}
                .catalogue-price{id: "catalogue-box-price-#{i}"}
                .catalogue-name{id: "catalogue-box-name-#{i}"}
                .catalogue-merchant{id: "catalogue-box-merchant-#{i}"}
    .span2
      .row-fluid
        #collection-items
          = render @collection.collection_items

:javascript
  $(document).ready(function() {
    monitorCollectionItems();
    window.catalogue = new Catalogue(16, #{@collection.id});
    $("#catalogue-add-shuffle").on("click", function(e) {
      createItemsFromFeed(window.catalogue.shuffle(40), e);
    });
    $("#catalogue-add-top").on("click", function(e) {
      createItemsFromFeed(window.catalogue.top(40), e);
    });
    $("#catalogue-add-urls").on("click", function() {
      showAddUrlsModal();
    });
    $("#catalogue-add-custom").on("click", function() {
      showAddCustomModal();
    });
  });
  function showAddUrlsModal() {
    $("#catalogue-add-urls-modal").removeClass('hidden');
    $("#catalogue-add-urls-modal").modal('show');
    $('#catalogue-add-urls-confirm').on('click', function() {
      $('#catalogue-add-urls-confirm').button('loading')
      $('#catalogue-add-urls-form').submit();
    });
  }
  function createItemsFromFeed(feed, event) {
    $("#" + event.target.id).button('loading');
    $.ajax({
      url: "#{admin_collection_items_path}",
      dataType: "script",
      data: {feed:JSON.stringify(feed), collection_id:#{@collection.id}},
      type: "post",
      error: function() {
        $("#" + event.target.id).button('reset');
      },
      success: function(data) {
        $("#" + event.target.id).button('reset');
      }
    });
  }
  function showAddCustomModal() {
    $("#catalogue-add-custom-modal").removeClass('hidden');
    $("#catalogue-add-custom-modal").modal('show');
    $('#catalogue-add-custom-confirm').on('click', function() {
      $('#catalogue-add-custom-confirm').button('loading')
        feed = {};
        feed["product_url"] = $("#custom-url").val();
        feed["image_url"] = $("#custom-image-url").val();
        feed["name"] = $("#custom-name").val();
        feed["brand"] = $("#custom-brand").val();
        feed["description"] = $("#custom-description").val();
        feed["price"] = $("#custom-price").val();
        feed["price_shipping"] = $("#custom-price-shipping").val();
        feed["shipping_info"] = $("#custom-shipping-info").val();
        feed["saturn"] = "0"
        $.ajax({
          url: "#{admin_collection_items_path}",
          dataType: "script",
          data: {feed:JSON.stringify([feed]), collection_id:#{@collection.id}},
          type: "post",
          error: function() {
            $('#catalogue-add-custom-confirm').button('reset');
            $("#catalogue-add-custom-modal").modal('hide');
          },
          success: function(data) {
            $('#catalogue-add-custom-confirm').button('reset');
            $("#catalogue-add-custom-modal").modal('hide');
          }
        });        
    });
  }

app/views/admin/collections/_form.html.haml
= form_for [:admin,@collection], html:{class:'form-inline'}, remote: georges do |f|
  - if !georges
    = f.text_field :name, type:"text", placeholder:"Name"
    = f.select :public, [['Public', true], ['Private', false]]
    = f.file_field :image
  = f.submit "#{georges ? 'Attach' : 'Update'}", class:"btn btn-success"

app/views/admin/collections/_modal.html.haml
#catalogue-add-urls-modal.modal.fade.hidden
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", type: "button"} x
        %h4.modal-title Add products by url
      .modal-body
        = form_tag admin_collection_items_path, id:"catalogue-add-urls-form", remote:true do
          %p Enter URLs of products to add (one URL per line)
          = text_area_tag "urls", "", rows:"10", cols:"80", style:"width:95%", id:"catalogue-add-urls-field"
          = hidden_field_tag "collection_id", collection.id
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        %button.btn.btn-primary#catalogue-add-urls-confirm{type: "button", "data-loading-text" => "Processing..."} Add products

#catalogue-add-custom-modal.modal.fade.hidden
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", type: "button"} x
        %h4.modal-title Add custom product
      .modal-body
        .row-fluid
          .span12
            %p Product url
            = text_field_tag "url", "", id:"custom-url", style:"width:97%"
        .row-fluid
          .span6
            %p Product name
            = text_field_tag "name", "", id:"custom-name", style:"width:95%"
            %p Product brand
            = text_field_tag "brand", "", id:"custom-brand", style:"width:95%"
            %p Price (EUR in cents)
            = text_field_tag "price", "", id:"custom-price", style:"width:95%"
            %p Image url
            = text_field_tag "image-url", "", id:"custom-image-url", style:"width:95%"
          .span6
            %p Product description
            = text_area_tag "description", "", rows:"4", style:"width:95%", id:"custom-description"
            %p Shipping price (EUR in cents)
            = text_field_tag "shipping_price", "", id:"custom-price-shipping", style:"width:95%"
            %p Shipping info
            = text_field_tag "shipping_info", "", id:"custom-shipping-info", style:"width:95%"
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        %button.btn.btn-primary#catalogue-add-custom-confirm{type: "button", "data-loading-text" => "Processing..."} Add product

app/views/admin/collections/edit.html.haml
%section.header
  %header
    %h1 Collection
    %h2= @collection.name
    .collection-header-title
      = image_tag @collection.image.url, style:"max-height: 100px;" if @collection.image.present?  

.container-fluid
  .row-fluid
    = render "builder" , georges: false

= render "modal", collection:@collection

app/views/admin/collections/index.html.haml
%section.header
  %header
    %h1 Collections
    %h2 Inspiring our users
    .action-buttons
      %a.btn.btn-large.btn-success{href: new_admin_collection_path, type: "button"}
        %i.icon-plus.icon-white
        New collection

.container-fluid
  .row-fluid
    .span2
      %article.coolbox
        %h3 Scope
        %select.input-medium.filter-option#publicFilter
          %option{value:1} Public
          %option{value:0} Private
      %article.coolbox
        %h3 Tags
        - @tags.each do |tag|
          = raw collection_tag_to_html(tag)
    .span10
      %article.coolbox
        %h3 Collections list
        %table.table.table-striped#collections
          %thead
            %tr
              %th Rank
              %th Name
              %th Cover
              %th Tags
              %th Items
          %tbody
            - @collections.each do |collection|
              %tr
                %td
                  %a.btn.btn-info.collection-up{href:"#{up_admin_collection_path(collection)}"}
                    %i.icon-arrow-up.icon-white
                  %strong= collection.rank
                  %a.btn.btn-info.collection-down{href:"#{down_admin_collection_path(collection)}"}
                    %i.icon-arrow-down.icon-white
                %td= link_to (collection.name.blank? ? collection.uuid : collection.name), admin_collection_path(collection)
                %td= collection.image.present? ? image_tag(collection.image.url, style:"max-width:300px;") : ""
                %td
                  - collection.tags.map(&:name).each do |tag|
                    = raw collection_tag_to_html(tag)
                %td= collection.collection_items.count

app/views/admin/collections/new.html.haml
%section.header
  %header
    %h1 New Collection
    %h2= @collection.uuid

= render "builder", georges: false
= render "modal", collection: @collection

app/views/admin/collections/show.html.haml
%section.header
  %header
    %h1 Collection
    %h2= @collection.name
    .action-buttons
      %a.btn.btn-large.btn-success{href: edit_admin_collection_path(@collection), type: "button"}
        %i.icon-edit.icon-white
        Edit collection
    .collection-header-title
      = image_tag @collection.image.url, style:"max-height: 100px;" if @collection.image.present?


.container-fluid
  .row-fluid
    = render @collection.collection_items

:javascript
  $(document).ready(function() {
    monitorCollectionItems();
  });

app/views/admin/collections/update.js.erb
$("#chat-feature").empty();
$('#chat-feature').hide();
$("#live-traces-container").show();
var content = $("#message_collection_uuid");
content.val("<%= escape_javascript(@collection.uuid)%>");
var link = $("#collection-link");
link.remove();
content.after("<%= escape_javascript(render "admin/georges/messages/collection_link") %>");